### ISSUE TITLE
config error_page directive doesn't work😢 

### ISSUE THREAD

**Issue by tkomatsu** [tkomatsu/webserv#47]
下記設定でwebservを起動すると、`config_.GetErrorPages(request_.GetURI());`で`std::runtime_error`例外が投げられてしまいます。
`config_.GetErrorPagaes("/");`でも同様に例外が投げられてしまいます。

`default.conf`
```nginx
error_page 405 ./docs/html/50x.html;

server {
	listen 4200;
}

server {
	listen 4201;
}

server {
	listen 4202;
}
```

例外が投げられているのは、`config.cpp`の135行目であることを確認しました。
https://github.com/tkomatsu/webserv/blob/0308198a27cf067133f820a3aa6cd36772471f90/srcs/config.cpp#L133-L150

b8f8cb649b89053e556494f6187d62fde26486ec のコミットで同様の状態になると思います。
現時点のmainブランチからの変更点は`Client::HandleException()`にconfigからディレクティブを取得するように変更した点です。
`WebServ`クラスは条件文のネストを浅くしただけで、処理は変わっていません。

**Comment by sasakiyudai** [comment]
今のconfigの仕様でlocationディレクティブが一個もないと、いかなるgetterもno location specifiedエラーになりますね。

**Comment by tkomatsu** [comment]
Configファイルのエラーの場合はそもそもプログラム自体を終了させてしまっていいんですかね。

**Comment by sasakiyudai** [comment]
今のwebservの仕様的に、rootではなくaliasだけでやっているのでlocationディレクティブが少なくともひとつ必要。なので
・configの読み込み時点でlocationを持たないサーバーが一つでもあれば、そこでconfig error出して終了
