### ISSUE TITLE
configのindexesで優先順位の情報がない

### ISSUE THREAD

**Issue by sasakiyudai** [tkomatsu/webserv#49]
configのindex directiveは左から右にファイルを見ていく。
したがってsetからvectorなどにする必要がある。

コンテキスト間での優先順位を保持するのが難しい。

**Comment by tkomatsu** [comment]
重複すると探す時に無駄が出ると思ってsetにしてもらってました。
`index hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html hello.html index.html;`
みたいな時に、無駄に`hello.html`を複数回確認することになってパフォーマンスが良くなさそうだなと。

順序を持った重複なしのコンテナがあるといいんですけどね、、、、。
