### ISSUE TITLE
リクエストが未対応のメソッドの場合にwebserv自体が終了してしまう

### ISSUE THREAD

**Issue by tkomatsu** [tkomatsu/webserv#65]
### Server
```log
$ ./webserv conf/default.conf
RequestFatalException: Invalid method
URI is not defined
```
### Client
```log
$ curl localhost:80 -X UNKNOWN
curl: (52) Empty reply from server
```

**Comment by sasakiyudai** [comment]
リクエストが来る
→ RecvRequest()のAppendRawdata()が呼ばれる
→ ParseStartline()でRequestFatalException("Invalid method")が投げられる
→ RecvRequest()のなかでcatchされ、ft::HttpResponseException("400")が投げられる
→ Activate()のなかでcatchされる。
→ HandleException()のなかでGetURI()がよばれる
→ uriがセットされていないのでRequestFatalException("URI is not defined")が投げられる
→ mainでcatchされる

という感じですね。
