### ISSUE TITLE
ファイルのアップロードはファイル名が指定できないのは問題ないですか？

### ISSUE THREAD

**Issue by tkomatsu** [tkomatsu/webserv#69]
課題文では
> Client should be able to upload files.

とだけ記載されているので、ファイル名を指定できるようにする必要はないとも取れます。

先人たちのDiscordでのやりとりを見ると、（テスターの関係かもしれませんが）ファイル名を指定できるようにしているようです。
過去の課題文では
> make the route able to accept uploaded files and configure where it should be saved

とあり、保存先を設定できるようにするとあります。
新しい課題の仕様では、ファイル名を指定してアップロードする必要はないという認識でいいでしょうか？

**Comment by sasakiyudai** [comment]
nginxのuploadモジュール的には

[nginxのレファレンス](https://mogile.web.fc2.com/nginx_wiki/nginx_wiki201510/modules/upload.html#:~:text=%E5%87%BA%E5%8A%9B%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D%E3%81%AF10%E6%A1%81%E3%81%8B%E3%82%89%E6%88%90%E3%82%8A)
> 出力ファイル名は10桁から成り、proxy_temp_path directive と同じアルゴリズムを使って生成されます。

とあり、実際に[こんな感じ](https://serverfault.com/questions/475755/nginx-upload-module-and-file-names)
に生成されるので、ファイル名は気にしなくていいと思います。

**Comment by tkomatsu** [comment]
`.html`の拡張子は外して時間だけのファイル名にして保存するように変更。
