### ISSUE TITLE
setsockopt周辺を正しくいじってit should not workにする

### ISSUE THREAD

**Issue by sasakiyudai** [tkomatsu/webserv#92]

**Comment by tkomatsu** [comment]
> 2個目は一つのconfigの中に複数のサーバーディレクティブ作って同じポート設定してnginx的にconflict起きてるから動かない
3個目は複数の、同じポートだけど違うconfigを使って複数の./webservを実行→既にポート使われてるから動かない
っていう単純なことだったかもしれない

by syudai

これにて解決
